# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: java-microservices-aca-lab

workflows:
  up:
    - azd: provision
    # - azd: package --all
    # - azd: deploy --all

infra:
  provider: bicep
  path: infra/bicep

services:
  api-gateway:
    resourceName: api-gateway
    project: ./src/spring-petclinic-api-gateway
    host: containerapp
    language: java
    docker:
      registry: ${AZURE_CONTAINER_REGISTRY_ENDPOINT}
      image: java-microservices-aca-lab/spring-petclinic-api-gateway
      tag: ${AZD_PROVISION_TIMESTAMP}
      remoteBuild: true

  customers-service:
    resourceName: customers-service
    project: ./src/spring-petclinic-customers-service
    host: containerapp
    language: java
    docker:
      registry: ${AZURE_CONTAINER_REGISTRY_ENDPOINT}
      image: java-microservices-aca-lab/spring-petclinic-customers-service
      tag: ${AZD_PROVISION_TIMESTAMP}
      remoteBuild: true

  vets-service:
    resourceName: vets-service
    project: ./src/spring-petclinic-vets-service
    host: containerapp
    language: java
    docker:
      registry: ${AZURE_CONTAINER_REGISTRY_ENDPOINT}
      image: java-microservices-aca-lab/spring-petclinic-vets-service
      tag: ${AZD_PROVISION_TIMESTAMP}
      remoteBuild: true

  visits-service:
    resourceName: visits-service
    project: ./src/spring-petclinic-visits-service
    host: containerapp
    language: java
    docker:
      registry: ${AZURE_CONTAINER_REGISTRY_ENDPOINT}
      image: java-microservices-aca-lab/spring-petclinic-visits-service
      tag: ${AZD_PROVISION_TIMESTAMP}
      remoteBuild: true

  chat-agent:
    resourceName: chat-agent
    project: ./src/spring-petclinic-chat-agent
    host: containerapp
    language: java
    docker:
      registry: ${AZURE_CONTAINER_REGISTRY_ENDPOINT}
      image: java-microservices-aca-lab/spring-petclinic-chat-agent
      tag: ${AZD_PROVISION_TIMESTAMP}
      remoteBuild: true

  admin-server:
    resourceName: admin-server
    project: ./src/spring-petclinic-admin-server
    host: containerapp
    language: java
    docker:
      registry: ${AZURE_CONTAINER_REGISTRY_ENDPOINT}
      image: java-microservices-aca-lab/spring-petclinic-admin-server
      tag: ${AZD_PROVISION_TIMESTAMP}
      remoteBuild: true

hooks:
  postprovision:
    posix:
      shell: sh
      run: ./infra/bicep/hooks/postprovision.sh
      interactive: true
      continueOnError: true

  predown:
    posix:
      shell: sh
      run: ./infra/bicep/hooks/predown.sh

  prepackage:
    posix:
      shell: sh
      run: 'cd src; chmod +x ./mvnw; ./mvnw clean package -DskipTests'
