# COMMON APPLICATION PROPERTIES

# embedded database init, supports mysql too trough the 'mysql' spring profile
spring:
  sql:
    init:
      schema-locations: classpath*:db/hsqldb/schema.sql
      data-locations: classpath*:db/hsqldb/data.sql
  jms:
    queue:
      visits-requests: visits-requests
      visits-confirmations: visits-confirmations
    servicebus:
      enabled: false  # disable messaging support by default
      namespace: ${SERVICEBUS_NAMESPACE}
      pricing-tier: premium
      passwordless-enabled: true
      credential:
        managed-identity-enabled: true
        client-id: ${CLIENT_ID}
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    # disable ribbon cache to facilate cache refresh
    loadbalancer:
      cache:
        enabled: false
    config:
      # Allow the microservices to override the remote properties with their own System properties or config file
      allow-override: true
      # Override configuration with any local property source
      override-none: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

# Spring Boot 1.5 makes actuator secure by default
management.security.enabled: false
# Enable all Actuators and not only the two available by default /health and /info starting Spring Boot 2.0
management.endpoints.web.exposure.include: "*"

# Temporary hack required by the Spring Boot 2 / Spring Cloud Finchley branch
# Waiting issue https://github.com/spring-projects/spring-boot/issues/13042
spring.cloud.refresh.refreshable: false


eureka:
  client:
    registryFetchIntervalSeconds: 20

# Logging
logging.level.org.springframework: INFO

# enable health probes
management.health.livenessState.enabled: true
management.health.readinessState.enabled: true
management.endpoint.health.probes.enabled: true

# Metrics
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true

# Chaos Engineering
---
spring:
  config:
    activate:
      on-profile: chaos-monkey
management.endpoint.chaosmonkey.enabled: true
chaos:
  monkey:
    enabled: true
    watcher:
      component: false
      controller: false
      repository: false
      rest-controller: false
      service: false

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/petclinic?useSSL=false
    username: root
    password: petclinic
  sql:
    init:
      schema-locations: classpath*:db/mysql/schema.sql
      data-locations: classpath*:db/mysql/data.sql
      mode: ALWAYS

