spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  # Web
  thymeleaf:
    mode: HTML
  # Internationalization
  messages:
    basename: messages/messages

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
